sudo: no

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
 - PYTEST_VERSION=4.6.3
 - PYTEST_VERSION=5.1.2

matrix:
  exclude:
    env: PYTEST_VERSION=5.1.2
    python: "2.7"

install:
  - pip install .
  - pip uninstall -y pytest
  - pip install pytest==$PYTEST_VERSION tox

script:
  - py.test test_mccabe.py
  - tox -e flake8
  - tox -e pyroma
  - tox -e check-manifest
