sudo: no

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
 - PYTEST_VERSION=2.6.4
 - PYTEST_VERSION=2.7.3
 - PYTEST_VERSION=2.8.2

install:
  - pip install .
  - pip uninstall -y pytest
  - pip install pytest==$PYTEST_VERSION tox

script:
  - py.test test_mccabe.py
  - tox -e pyflakes
  - tox -e pep8
  - tox -e pyroma
  - tox -e check-manifest
